### ISSUE TITLE
SSP tests fail if you try to rerun them

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#1021]
If you try to rerun an SSP test, you get an error like this:

```
2020-05-23 17:15:34: Exception during run:
[Errno 17] File exists
Traceback (most recent call last):
  File "/glade/work/sacks/ctsm_code/current_branch1/cime/scripts/Tools/../../scripts/lib/CIME/SystemTests/system_tests_common.py", line 151, in run
    self.run_phase()
  File "/glade/work/sacks/ctsm_code/current_branch1/cime_config/SystemTests/ssp.py", line 86, in run_phase
    os.symlink(item, os.path.join(rundir, os.path.basename(item)))
OSError: [Errno 17] File exists
```

It looks like this should be as easy as wrapping the `os.symlink` call in a conditional. I'll take a stab at it.

**Comment by billsacks** [comment]
I have tested with 4665c9ce138402076362133986823c5cb2e8928c, and that indeed resolves this issue. I'll bring that to master very soon.
