### ISSUE TITLE
LILACSMOKE test fails if you explicitly add _Vnuopc to the test name

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#1588]
### Brief summary of bug

The LILACSMOKE test in the test suite is `LILACSMOKE_D_Ld2.f10_f10_mg37.I2000Ctsm50NwpSpAsRs.cheyenne_intel.clm-lilac`. This test currently works, but if you explicitly add `_Vnuopc` (`LILACSMOKE_Vnuopc_D_Ld2.f10_f10_mg37.I2000Ctsm50NwpSpAsRs.cheyenne_intel.clm-lilac`), it fails with this error:

```
Finished MODEL_BUILD for test LILACSMOKE_Vnuopc_D_Ld2.f10_f10_mg37.I2000Ctsm50NwpSpAsRs.cheyenne_intel in 308.848313 seconds (FAIL). [COMPLETED 1 of 1]
    Case dir: /glade/scratch/sacks/LILACSMOKE_Vnuopc_D_Ld2.f10_f10_mg37.I2000Ctsm50NwpSpAsRs.cheyenne_intel.20220102_080520_y62dca
    Errors were:
        Building test for LILACSMOKE in directory /glade/scratch/sacks/LILACSMOKE_Vnuopc_D_Ld2.f10_f10_mg37.I2000Ctsm50NwpSpAsRs.cheyenne_intel.20220102_080520_y62dca
        Traceback (most recent call last):
          File "./case.build", line 167, in <module>
            _main_func(__doc__)
          File "./case.build", line 156, in _main_func
            success = test.build(sharedlib_only=sharedlib_only, model_only=model_only, ninja=ninja, dry_run=dry_run, separate_builds=separate_builds)
          File "/glade/work/sacks/ctsm_code/ctsm/cime/scripts/Tools/../../scripts/lib/CIME/SystemTests/system_tests_common.py", line 96, in build
            model_only=(phase_name==MODEL_BUILD_PHASE))
          File "/glade/work/sacks/ctsm_code/ctsm/cime_config/SystemTests/lilacsmoke.py", line 83, in build_phase
            self._create_runtime_inputs()
          File "/glade/work/sacks/ctsm_code/ctsm/cime_config/SystemTests/lilacsmoke.py", line 155, in _create_runtime_inputs
            dst=os.path.join(runtime_inputs, 'user_nl_ctsm'))
          File "/glade/u/apps/ch/opt/python/3.7.9/gnu/9.1.0/lib/python3.7/shutil.py", line 120, in copyfile
            with open(src, 'rb') as fsrc:
        FileNotFoundError: [Errno 2] No such file or directory: '/glade/scratch/sacks/LILACSMOKE_Vnuopc_D_Ld2.f10_f10_mg37.I2000Ctsm50NwpSpAsRs.cheyenne_intel.20220102_080520_y62dca/user_nl_ctsm'
```

### General bug information

**CTSM version you are using:** ctsm5.1.dev069

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** Just this LILACSMOKE test, and only when adding the `_Vnuopc` qualifier.

### Details of bug

I'm not sure why adding an explicit `_Vnuopc` leads to this failure, since `COMP_INTERFACE` is `nuopc` in either case (and I'm not sure why the `COMP_INTERFACE` would impact whether `user_nl_ctsm` is copied in to the case directory anyway). I don't feel this is worth digging into further, but I wanted to open this issue for the record.

(Originally reported by @mvertens .)

**Comment by billsacks** [comment]
Closing as a wontfix.

**Comment by billsacks** [comment]
Wait, I think I completely misdiagnosed this: I just noticed that the tests that were failing didn't have the testmods directory, `clm-lilac`. It's almost certainly the lack of that testmods directory, and not the addition of `_Vnuopc`, that is responsible for the issue. That makes a lot more sense now.
