### ISSUE TITLE
Have python scripts do try, except when attempting to download NEON data

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1594]
### Brief summary of bug

In trying out the run_neon and modify_neon scripts I noticed an awkward error that results when the data is attempted to be downloaded from the Amazon S3 bucket and it fails.

### General bug information

**CTSM version you are using:** ctsm5.1.dev068-95-g72261e381

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** 
### Details of bug

run_neon and modify_singlept_site_neon.py scripts

### Important details of your setup / configuration so we can reproduce the bug

Normally this works. But, it does appear that periodically there are issues with the download. I'm not sure how often it happens, but it's often enough that you can see it.

### Important output or errors that show the problem

```
Traceback (most recent call last):
  File "/glade/u/apps/ch/opt/python/3.7.9/gnu/9.1.0/pkg-library/20201220/lib/python3.7/site-packages/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/glade/u/apps/ch/opt/python/3.7.9/gnu/9.1.0/pkg-library/20201220/lib/python3.7/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/glade/u/apps/ch/opt/python/3.7.9/gnu/9.1.0/pkg-library/20201220/lib/python3.7/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/glade/u/apps/ch/opt/python/3.7.9/gnu/9.1.0/pkg-library/20201220/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/glade/u/apps/ch/opt/python/3.7.9/gnu/9.1.0/pkg-library/20201220/lib/python3.7/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/glade/u/apps/ch/opt/python/3.7.9/gnu/9.1.0/pkg-library/20201220/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/glade/u/apps/ch/opt/python/3.7.9/gnu/9.1.0/pkg-library/20201220/lib/python3.7/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/glade/u/apps/ch/opt/python/3.7.9/gnu/9.1.0/pkg-library/20201220/lib/python3.7/site-packages/urllib3/connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x2acd7d048d10>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/glade/u/apps/ch/opt/python/3.7.9/gnu/9.1.0/pkg-library/20201220/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/glade/u/apps/ch/opt/python/3.7.9/gnu/9.1.0/pkg-library/20201220/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/glade/u/apps/ch/opt/python/3.7.9/gnu/9.1.0/pkg-library/20201220/lib/python3.7/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='neon-ncar.s3.data.neonscience.org', port=443): Max retries exceeded with url: /listing.csv (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2acd7d048d10>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

This is the error message I saw...

Traceback (most recent call last):
  File "/glade/work/erik/ctsm_worktrees/neon/tools/site_and_regional/modify_singlept_site_neon.py", line 706, in <module>
    main()
  File "/glade/work/erik/ctsm_worktrees/neon/tools/site_and_regional/modify_singlept_site_neon.py", line 508, in main
    file_time = check_neon_time()
  File "/glade/work/erik/ctsm_worktrees/neon/tools/site_and_regional/modify_singlept_site_neon.py", line 441, in check_neon_time
    download_file(url, listing_file)
  File "/glade/work/erik/ctsm_worktrees/neon/tools/site_and_regional/modify_singlept_site_neon.py", line 460, in download_file
    response = requests.get(url)
  File "/glade/u/apps/ch/opt/python/3.7.9/gnu/9.1.0/pkg-library/20201220/lib/python3.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/glade/u/apps/ch/opt/python/3.7.9/gnu/9.1.0/pkg-library/20201220/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/glade/u/apps/ch/opt/python/3.7.9/gnu/9.1.0/pkg-library/20201220/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/glade/u/apps/ch/opt/python/3.7.9/gnu/9.1.0/pkg-library/20201220/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/glade/u/apps/ch/opt/python/3.7.9/gnu/9.1.0/pkg-library/20201220/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='neon-ncar.s3.data.neonscience.org', port=443): Max retries exceeded with url: /listing.csv (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2acd7d048d10>: Failed to establish a new connection: [Errno 110] Connection timed out'))
```

**Comment by ekluzek** [comment]
I think the answer to this is to just add a try, except block around the point where data is downloaded in the scripts. Then it should be able to shut down cleanly when there is trouble with the data download. The problem with the above error is it's difficult to figure out what actually wrong.

**Comment by negin513** [comment]
Thanks. I agree that if the server times out it gives the long un-readble error. 

I have already put it some error catching if the download fails from server or is unavailable by checking the status_code but I agree that this does not work when the server times out:
https://github.com/ESCOMP/CTSM/blob/57175712e10e443f37818c81b8e14c956f28de34/tools/site_and_regional/modify_singlept_site_neon.py#L465-L469

For avoiding the times out error I am using try except block as @ekluzek recommends:
```python
    try: 
        response = requests.get(url)
            
        with open(fname, "wb") as f:
            f.write(response.content)
            
        # -- Check if download status_code
        if response.status_code == 200:
            print("Download finished successfully for", fname, ".")
        elif response.status_code == 404:
            print("File " + fname + "was not available on the neon server:" + url)
    except Exception as err:
        print ('The server could not fulfill the request.')                                                                  
        print ('Something went wrong in downloading', fname)
        print ('Error code:', err.code)

```
@ekluzek do you think this would help make the readability in case of times out error. Thanks again for pointing this out.

**Comment by ekluzek** [comment]
Yes that looks really good to me. You handle two possible errors. For the generic error I wonder about tweaking the error message a bit. Should it mention that this is likely a timeout? The question that the user will want to know is "what do I do about this"? So do we suggest to them that they try again? Or wait and try again? I'm not quite sure what's happening here, so it's hard to give guidance. Are there other error codes that can be checked against? Maybe one that has something to do with the timeout?

In general other possible errors I can think of, might be your disk is full, or you don't have permission to write, or it's a bad filename. I'm not sure how many of those we want to handle, but because this time-out issue is common we do want to handle it.

**Comment by negin513** [comment]
> Yes that looks really good to me. You handle two possible errors. For the generic error I wonder about tweaking the error message a bit. Should it mention that this is likely a timeout? The question that the user will want to know is "what do I do about this"? So do we suggest to them that they try again? Or wait and try again? I'm not quite sure what's happening here, so it's hard to give guidance. Are there other error codes that can be checked against? Maybe one that has something to do with the timeout?
> 
> In general other possible errors I can think of, might be your disk is full, or you don't have permission to write, or it's a bad filename. I'm not sure how many of those we want to handle, but because this time-out issue is common we do want to handle it.

@ekluzek Thanks! these are really good points you are bring up. Honestly, I was quite surprised by this error as well and not sure what might have caused it. I have two guesses for this situation:
1) An issue with the server so the requests for downloads kept pending for some time and then it receive the time-out error.
2) The code was being used on Cheyenne interactive nodes. I think on Cheyenne interactive nodes the download feature might be limited... I actually had a similar issue while using another code for downloading neon evaluation data from S3 on the Cheyenne interactive nodes. I will look into this issue further tomorrow.

I also have to look further into what kinds of `response.status_code` are possible. I think they directly come HTTP response status code. But most are not relevant for us (e.g. `Payment Required`). However, 408 is `Request Timeout`. 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

I think probably 200 and 404 are the most relavant ones (200 is `OK`, 404 is `Not Found`):
https://www.geeksforgeeks.org/response-status_code-python-requests/

I will look more into these points.

**Comment by wwieder** [comment]
Thanks for finding this @ekluzek and improving the error messages, @negin513
