### ISSUE TITLE
Missing path

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1754]
### Brief summary of bug

The Path to get the python modules under cime/CIME/Tools is incorrect.

### General bug information

**CTSM version you are using:** ctsm5.1.dev095

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:**

python tools that need the right path for CIME/Tools

### Details of bug

@jedwards4b has the fix for this in #1750

### Important output or errors that show the problem

This seems to work on izumi, but can fail under python environments in Cheyenne.

make utest fails as follows... (make stest works)

```
ERROR: test.test_unit_run_sys_tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test.test_unit_run_sys_tests
Traceback (most recent call last):
  File "/glade/work/erik/conda-envs/ctsm_py/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/glade/work/erik/conda-envs/ctsm_py/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/glade/work/erik/ctsm_worktrees/quickfix/python/ctsm/test/test_unit_run_sys_tests.py", line 19, in <module>
    from ctsm.run_sys_tests import run_sys_tests
  File "/glade/work/erik/ctsm_worktrees/quickfix/python/ctsm/run_sys_tests.py", line 10, in <module>
    from CIME.test_utils import get_tests_from_xml  # pylint: disable=import-error
ModuleNotFoundError: No module named 'CIME'
```

**Comment by ekluzek** [comment]
Duplicate of #1749
