### ISSUE TITLE
tools tests fail for NEON list on izumi

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1905]
### Brief summary of bug

The tools test list for NEON fails in ctsm5.1.dev113 on izumi

### General bug information

**CTSM version you are using:** ctsm5.1.dev113
**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** 
Tools test list in test/tools for NEON on izumi
standard test list works on cheyenne and izumi. And the NEON test list works for cheyenne.

### Details of bug

`env CLM_INPUT_TESTS=`pwd`/tests_pretag_nompi_neon ./test_driver.sh -i`

#### Important output or errors that show the problem

> 001 sm0a1 TSMscript_tools.sh site_and_regional run_neon.py run_neon_OSBS ........................ rc=6 FAIL
> 003 smaa2 TSMscript_tools.sh site_and_regional modify_singlept_site_neon.py modify_data_YELL .... rc=6 FAIL
> 005 smba1 TSMscript_tools.sh site_and_regional subset_data subset_data_YELL ..................... rc=6 FAIL
> 007 smbb1 TSMscript_tools.sh site_and_regional subset_data subset_data_KONA ..................... rc=6 FAIL
> 009 smb81 TSMscript_tools.sh site_and_regional subset_data subset_data_US-UMB ................... rc=6 FAIL
> 011 smbc1 TSMscript_tools.sh site_and_regional subset_data subset_data_f09_US_pt ................ rc=6 FAIL
> 013 smbd1 TSMscript_tools.sh site_and_regional subset_data subset_data_region1 .................. rc=6 FAIL

**Comment by ekluzek** [comment]
Note, one problem is that the py_env_create call isn't working since it needs to reference $CLM_ROOT and that's set after it's being done.

See this error...

`./test_driver_izumi_15:42:13.sh: line 59: /py_env_create: No such file or directory`

**Comment by ekluzek** [comment]
Note tools testing was done previously in:

ctsm5.1.dev104 -- cheyenne
ctsm5.1.dev100 -- cheyenne/izumi
ctsm5.1.dev096 -- cheyenne-neon
ctsm5.1.dev095 -- cheyenne

**Comment by ekluzek** [comment]
Error for modify_surfdata is:

```
sv': '2022-03-15 10:32:14'}
/fs/cgd/csm/inputdata/lnd/clm2/surfdata_map/NEON/surfdata_*hist_78pfts_CMIP6_simyr2000_YELL*.nc
Traceback (most recent call last):
  File "/scratch/cluster/erik/ctsm5.1.dev113/tools/site_and_regional/modify_singlept_site_neon.py", line 712, in <module>
    main()
  File "/scratch/cluster/erik/ctsm5.1.dev113/tools/site_and_regional/modify_singlept_site_neon.py", line 520, in main
    surf_file = find_surffile(surf_dir, site_name)
  File "/scratch/cluster/erik/ctsm5.1.dev113/tools/site_and_regional/modify_singlept_site_neon.py", line 268, in find_surffile
    "Surface data for this site " + site_name + "was not found:" + surf_file,
TypeError: can only concatenate str (not "list") to str
```

Error for subset_data is:

```
INFO: User = erik
INFO: Current directory = /scratch/cluster/erik/clmTests/test-driver.176905/TSMscript_tools.site_and_regional.subset_data.subset_data_KONA
INFO: ----------------------------------------------------------------------------
INFO: This script extracts a single point from the global CTSM datasets.
INFO:  - dominant pft(s) : [17, 19, 23, 45]
INFO:  - percentage of dominant pft(s) : [28.0, 12.0, 32.0, 28.0]
INFO: ----------------------------------------------------------------------
INFO: Creating domain file at 263.38956, 39.1082.
INFO: fdomain_in:  /glade/p/cesmdata/inputdata/share/domains/domain.lnd.fv0.9x1.25_gx1v7.151020.nc
INFO: fdomain_out: /scratch/cluster/erik/clmTests/test-driver.176905/TSMscript_tools.site_and_regional.subset_data.subset_data_KONA/KONA_user-mod_and_data/domain.lnd.fv0.9x1.25_gx1v7_KONA_c221116.nc
ERROR: File not found : /glade/p/cesmdata/inputdata/share/domains/domain.lnd.fv0.9x1.25_gx1v7.151020.nc
```

So subset_data is assuming a particular path for inputdata, we should give a better error for the user on this.

**Comment by ekluzek** [comment]
This was fixed in ctsm5.1.dev114
