### ISSUE TITLE
modify_singlept_site_neon.py can't work on izumi, because of bad conda environment

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1910]
### Brief summary of bug

modify_singlept_site_neon.py, fails to run on izumi, because the version of pandas in the conda environment when using py_env_create for what's used in python than what we've specified in the conda environment.

### General bug information

**CTSM version you are using:** ctsm5.1.dev114

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** running modify_singlept_site_neon on izumi

### Details of bug

conda claims that the version of pandas used is:

pandas                    1.3.5

But, internally pd.__version__ shows...

0.23.4

and pd.show_versions() also shows that pandas is older than what's used in the conda environment.

### Important details of your setup / configuration so we can reproduce the bug

I think this is really a problem of the conda environment in izumi more so than a problem with the python script itself. The method used requires at least version 1.1.0.

### Important output or errors that show the problem

```
Traceback (most recent call last):
  File "/fs/cgd/data0/erik/ctsm_worktree/neon/tools/site_and_regional/modify_singlept_site_neon.py", line 722, in <module>
    main()
  File "/fs/cgd/data0/erik/ctsm_worktree/neon/tools/site_and_regional/modify_singlept_site_neon.py", line 663, in main
    fill_interpolate(f2, "PCT_CLAY", method)
  File "/fs/cgd/data0/erik/ctsm_worktree/neon/tools/site_and_regional/modify_singlept_site_neon.py", line 504, in fill_interpolate
    tmp = tmp_df.to_numpy()
  File "/usr/local/anaconda-3.7.0/lib/python3.7/site-packages/pandas/core/generic.py", line 4376, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'to_numpy'
```

**Comment by ekluzek** [comment]
I'm going to leave this as a failing issue. We'll need to work on the conda environment in izumi for this (and there's also a couple related issues): #1821, #1786, #1658 that I think all boil down to this problem. The way around it might be to endorse having people download their own version of conda for use on izumi.

**Comment by ekluzek** [comment]
The one thing I will put in place is to check the panda's version and fail if it's too old.

**Comment by ekluzek** [comment]
After logging into a new terminal on izumi, this seems to work fine now.  So I'll close this with the creation of ctsm5.1.dev114.

**Comment by ekluzek** [comment]
I was wrong in the last message, the izumi conda environment needs more exploration, but izumi is also down now.

**Comment by ekluzek** [comment]
conda has been updated now on izumi, so I don't think this is a problem any more.
