### ISSUE TITLE
run_ctsm_py_tests failures at os.getcwd()

### ISSUE THREAD

**Issue by samsrabin** [ESCOMP/CTSM#2167]
### Brief summary of bug

15 Python tests fail when called using `python/run_ctsm_py_tests`.

### General bug information

**CTSM version you are using:** ctsm5.1.dev141

**Does this bug cause significantly incorrect results in the model's science?** No

### Details of bug

@billsacks pointed out that this is probably due to some test not changing out of a temporary directory before the directory is destroyed. It's probably in `test_sys_mesh_modifier.py`, as that script has a `os.chdir(self._tempdir)` but never leaves.

### Important output or errors that show the problem

```
.................Setting resource.RLIMIT_STACK to -1 from (-1, -1)
Done converting /var/tmp/pbs.3388722.chadmin1.ib0.cheyenne.ucar.edu/tmpq6guv6yc/scrip.nc
...........................................................................................EEEEEE......................................EEEEEEEEE....................
======================================================================
ERROR: test_createTestCommand_testfileAndExtraArgs (test.test_unit_run_sys_tests.TestRunSysTests)
The correct create_test command should be run with a testfile and extra arguments
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/glade/u/home/samrabin/ctsm_testmerge-20230918/python/ctsm/test/test_unit_run_sys_tests.py", line 36, in setUp
    self._original_wd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory

======================================================================
ERROR: test_createTestCommand_testnames (test.test_unit_run_sys_tests.TestRunSysTests)
The correct create_test command should be run when providing a list of test names
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/glade/u/home/samrabin/ctsm_testmerge-20230918/python/ctsm/test/test_unit_run_sys_tests.py", line 36, in setUp
    self._original_wd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory

======================================================================
ERROR: test_createTestCommands_testsuite (test.test_unit_run_sys_tests.TestRunSysTests)
The correct create_test commands should be run with a test suite
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/glade/u/home/samrabin/ctsm_testmerge-20230918/python/ctsm/test/test_unit_run_sys_tests.py", line 36, in setUp
    self._original_wd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory

======================================================================
ERROR: test_createTestCommands_testsuiteSpecifiedCompilers (test.test_unit_run_sys_tests.TestRunSysTests)
The correct commands should be run with a test suite where compilers are specified
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/glade/u/home/samrabin/ctsm_testmerge-20230918/python/ctsm/test/test_unit_run_sys_tests.py", line 36, in setUp
    self._original_wd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory

======================================================================
ERROR: test_testroot_setup (test.test_unit_run_sys_tests.TestRunSysTests)
Ensure that the appropriate test root directory is created and populated
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/glade/u/home/samrabin/ctsm_testmerge-20230918/python/ctsm/test/test_unit_run_sys_tests.py", line 36, in setUp
    self._original_wd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory

======================================================================
ERROR: test_withDryRun_nothingDone (test.test_unit_run_sys_tests.TestRunSysTests)
With dry_run=True, no directories should be created, and no commands should be run
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/glade/u/home/samrabin/ctsm_testmerge-20230918/python/ctsm/test/test_unit_run_sys_tests.py", line 36, in setUp
    self._original_wd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory

======================================================================
ERROR: test_check_args_badconfig (test.test_unit_subset_data.TestSubsetData)
Test that check args aborts when a config file is entered that doesn't exist
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/glade/u/home/samrabin/ctsm_testmerge-20230918/python/ctsm/test/test_unit_subset_data.py", line 34, in setUp
    DEFAULTS_FILE = os.path.join(os.getcwd(), "ctsm/test/testinputs/default_data.cfg")
FileNotFoundError: [Errno 2] No such file or directory

======================================================================
ERROR: test_check_args_nooutput (test.test_unit_subset_data.TestSubsetData)
Test that check args aborts when no-output is asked for
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/glade/u/home/samrabin/ctsm_testmerge-20230918/python/ctsm/test/test_unit_subset_data.py", line 34, in setUp
    DEFAULTS_FILE = os.path.join(os.getcwd(), "ctsm/test/testinputs/default_data.cfg")
FileNotFoundError: [Errno 2] No such file or directory

======================================================================
ERROR: test_check_args_notype (test.test_unit_subset_data.TestSubsetData)
Test that check args aborts when no type is asked for
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/glade/u/home/samrabin/ctsm_testmerge-20230918/python/ctsm/test/test_unit_subset_data.py", line 34, in setUp
    DEFAULTS_FILE = os.path.join(os.getcwd(), "ctsm/test/testinputs/default_data.cfg")
FileNotFoundError: [Errno 2] No such file or directory

======================================================================
ERROR: test_check_args_outsurfdat_fails_without_create_surface (test.test_unit_subset_data.TestSubsetData)
Test that check args does not allow an output surface dataset to be specified
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/glade/u/home/samrabin/ctsm_testmerge-20230918/python/ctsm/test/test_unit_subset_data.py", line 34, in setUp
    DEFAULTS_FILE = os.path.join(os.getcwd(), "ctsm/test/testinputs/default_data.cfg")
FileNotFoundError: [Errno 2] No such file or directory

======================================================================
ERROR: test_check_args_outsurfdat_fails_without_overwrite (test.test_unit_subset_data.TestSubsetData)
Test that check args does not allow an output surface dataset to be specified
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/glade/u/home/samrabin/ctsm_testmerge-20230918/python/ctsm/test/test_unit_subset_data.py", line 34, in setUp
    DEFAULTS_FILE = os.path.join(os.getcwd(), "ctsm/test/testinputs/default_data.cfg")
FileNotFoundError: [Errno 2] No such file or directory

======================================================================
ERROR: test_check_args_outsurfdat_provided (test.test_unit_subset_data.TestSubsetData)
Test that check args allows an output surface dataset to be specified
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/glade/u/home/samrabin/ctsm_testmerge-20230918/python/ctsm/test/test_unit_subset_data.py", line 34, in setUp
    DEFAULTS_FILE = os.path.join(os.getcwd(), "ctsm/test/testinputs/default_data.cfg")
FileNotFoundError: [Errno 2] No such file or directory

======================================================================
ERROR: test_inputdata_setup_files_bad_inputdata_arg (test.test_unit_subset_data.TestSubsetData)
Test that inputdata directory provided on command line does not exist if it's bad
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/glade/u/home/samrabin/ctsm_testmerge-20230918/python/ctsm/test/test_unit_subset_data.py", line 34, in setUp
    DEFAULTS_FILE = os.path.join(os.getcwd(), "ctsm/test/testinputs/default_data.cfg")
FileNotFoundError: [Errno 2] No such file or directory

======================================================================
ERROR: test_inputdata_setup_files_basic (test.test_unit_subset_data.TestSubsetData)
Test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/glade/u/home/samrabin/ctsm_testmerge-20230918/python/ctsm/test/test_unit_subset_data.py", line 34, in setUp
    DEFAULTS_FILE = os.path.join(os.getcwd(), "ctsm/test/testinputs/default_data.cfg")
FileNotFoundError: [Errno 2] No such file or directory

======================================================================
ERROR: test_inputdata_setup_files_inputdata_dne (test.test_unit_subset_data.TestSubsetData)
Test that inputdata directory does not exist
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/glade/u/home/samrabin/ctsm_testmerge-20230918/python/ctsm/test/test_unit_subset_data.py", line 34, in setUp
    DEFAULTS_FILE = os.path.join(os.getcwd(), "ctsm/test/testinputs/default_data.cfg")
FileNotFoundError: [Errno 2] No such file or directory

----------------------------------------------------------------------
Ran 181 tests in 12.957s

FAILED (errors=15)
```

**Comment by ekluzek** [comment]
@TeaganKing and @slevis-lmwg and I talked about this earlier.

@TeaganKing figured out that this is just when ./run_ctsm_py_tests is run without arguments. Using the "make all" that breaks it up into the system and unit tests it works fine. So it must be when it runs more tests together. And specifically running both unit and system tests at the same time. From looking at this I see this in version forward to ctsm5.1.dev147.

This should be easy to fix though with the suggestion about making sure you chdir to all tests to a specific location, and then chdir back at tear-down and then delete the temporary directory.
