### ISSUE TITLE
fates prt2 test runs out of wallclock time on izumi

### ISSUE THREAD

**Issue by rgknox** [ESCOMP/CTSM#2324]
This test...

ERS_D_Ld30.f45_f45_mg37.I2000Clm50FatesCruRsGs.izumi_nag.clm-FatesColdPRT2.G.0117-123114iz_nag

.. needs more JOB_WALLCLOCK_TIME.  Aside from bumping that value up (from 40 minutes!), we can also change the test, I don't think it needs to be debug, or we can try running for 20 days instead of 30.

**Comment by ekluzek** [comment]
Looking at the latest baselines this test is failing at CREATE_NEWCASE so should be looked into again.

**Comment by glemieux** [comment]
The failure on `CREATE_NEWCASE` appears to be due to the not being able to find `scipy.io` module:
```
FROM: /scratch/cluster/glemieux/ctsm-tests/tests_1004-102417iz/ERS_D_Ld30.f45_f45_mg37.I2000Clm50FatesCruRsGs.izumi_nag.clm-FatesColdPRT2.G.1004-102417iz_nag
  stat: 1

  errput: Traceback (most recent call last):
  File "/home/glemieux/ctsm-test/src/fates//tools/modify_fates_paramfile.py", line 35, in <module>
    from scipy.io import netcdf as nc
ImportError: No module named scipy.io
Traceback (most recent call last):
  File "/home/glemieux/ctsm-test/src/fates//tools/modify_fates_paramfile.py", line 35, in <module>
    from scipy.io import netcdf as nc
ImportError: No module named scipy.io
Leaving broken case dir /scratch/cluster/glemieux/ctsm-tests/tests_1004-102417iz/ERS_D_Ld30.f45_f45_mg37.I2000Clm50FatesCruRsGs.izumi_nag.clm-FatesColdPRT2.G.1004-102417iz_nag
ERROR: Command: '/scratch/cluster/glemieux/ctsm-tests/tests_1004-102417iz/ERS_D_Ld30.f45_f45_mg37.I2000Clm50FatesCruRsGs.izumi_nag.clm-FatesColdPRT2.G.1004-102417iz_nag/shell_commands' failed with error 'Traceback (most recent call last):
  File "/home/glemieux/ctsm-test/src/fates//tools/modify_fates_paramfile.py", line 35, in <module>
    from scipy.io import netcdf as nc
ImportError: No module named scipy.io
Traceback (most recent call last):
  File "/home/glemieux/ctsm-test/src/fates//tools/modify_fates_paramfile.py", line 35, in <module>
    from scipy.io import netcdf as nc
ImportError: No module named scipy.io' from dir '/scratch/cluster/glemieux/ctsm-tests/tests_1004-102417iz/ERS_D_Ld30.f45_f45_mg37.I2000Clm50FatesCruRsGs.izumi_nag.clm-FatesColdPRT2.G.1004-102417iz_nag'
```

**Comment by glemieux** [comment]
Actually I think #2335, is the better one to point to.

**Comment by wwieder** [comment]
This is a duplicated of #2335
