### ISSUE TITLE
Python system tests fail on Casper

### ISSUE THREAD

**Issue by samsrabin** [ESCOMP/CTSM#2402]
### Brief summary of bug

Python system tests fail on casper.

### General bug information

**CTSM version you are using:** `ctsm5.1.dev171`

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** n/a

### Details of bug

Tested on Casper under `ctsm_pylib`.

### Important details of your setup / configuration so we can reproduce the bug

Casper modules:
```
Currently Loaded Modules:
  1) ncarenv/23.10  (S)   3) ncarcompilers/1.0.0   5) ucx/1.14.1      7) hdf5/1.12.2    9) nco/5.1.9
  2) intel/2023.2.1       4) cuda/12.2.1           6) openmpi/4.1.6   8) netcdf/4.9.2
```

No problem on Derecho, which uses `ncarenv/23.09`—maybe that's the issue?
```
Currently Loaded Modules:
  1) ncarenv/23.09 (S)   3) intel/2023.2.1        5) cray-mpich/8.1.27   7) netcdf/4.9.2
  2) craype/2.7.23       4) ncarcompilers/1.0.0   6) hdf5/1.12.2         8) nco/5.1.9
```

I can't load 23.09 on Casper or 23.10 on Derecho to test.

### Important output or errors that show the problem
From `make stest`:
```
python3 ./run_ctsm_py_tests  --sys
................ERROR: FakeCase does not support getting value of 'GPU_OFFLOAD'
E..E
Stdout:
---- building a base case -------
---- creating a base case -------
---- base case created ------
---- base case setup ------

======================================================================
ERROR: test_allInfo (test.test_sys_mesh_modifier.TestSysMeshMaskModifier)
This test specifies all the information that one may specify
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/glade/u/home/samrabin/ctsm_pylib-update/python/ctsm/test/test_sys_mesh_modifier.py", line 66, in setUp
    subprocess.check_call(configure_cmd, shell=False)
  File "/glade/work/samrabin/conda-envs/ctsm_pylib/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/glade/u/home/samrabin/ctsm_pylib-update/cime/CIME/scripts/configure' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/glade/u/home/samrabin/ctsm_pylib-update/python/ctsm/test/test_sys_mesh_modifier.py", line 68, in setUp
    sys.exit(f"{e} ERROR using {configure_cmd}")
SystemExit: Command '/glade/u/home/samrabin/ctsm_pylib-update/cime/CIME/scripts/configure' returned non-zero exit status 1. ERROR using /glade/u/home/samrabin/ctsm_pylib-update/cime/CIME/scripts/configure

======================================================================
ERROR: test_one_site (test.test_sys_run_neon.TestSysRunNeon)
This test specifies a site to run
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/glade/u/home/samrabin/ctsm_pylib-update/python/ctsm/test/test_sys_run_neon.py", line 57, in test_one_site
    main("")
  File "/glade/u/home/samrabin/ctsm_pylib-update/python/ctsm/site_and_regional/run_neon.py", line 224, in main
    cesmroot, output_root, res, compset, overwrite, setup_only
  File "/glade/u/home/samrabin/ctsm_pylib-update/python/ctsm/site_and_regional/neon_site.py", line 101, in build_base_case
    case.case_setup()
  File "/glade/u/home/samrabin/ctsm_pylib-update/cime/CIME/case/case_setup.py", line 499, in case_setup
    is_batch=is_batch,
  File "/glade/u/home/samrabin/ctsm_pylib-update/cime/CIME/utils.py", line 2477, in run_and_log_case_status
    rv = func()
  File "/glade/u/home/samrabin/ctsm_pylib-update/cime/CIME/case/case_setup.py", line 462, in <lambda>
    self, caseroot, clean=clean, test_mode=test_mode, reset=reset, keep=keep
  File "/glade/u/home/samrabin/ctsm_pylib-update/cime/CIME/case/case_setup.py", line 290, in _case_setup_impl
    case.load_env()
  File "/glade/u/home/samrabin/ctsm_pylib-update/cime/CIME/case/case.py", line 2157, in load_env
    self._loaded_envs = env_module.load_env(self, job=job, verbose=verbose)
  File "/glade/u/home/samrabin/ctsm_pylib-update/cime/CIME/XML/env_mach_specific.py", line 140, in load_env
    modules_to_load, force_method=force_method, verbose=verbose
  File "/glade/u/home/samrabin/ctsm_pylib-update/cime/CIME/XML/env_mach_specific.py", line 169, in _load_modules
    self._load_module_modules(modules_to_load, verbose=verbose)
  File "/glade/u/home/samrabin/ctsm_pylib-update/cime/CIME/XML/env_mach_specific.py", line 461, in _load_module_modules
    "module command {} failed with message:\n{}".format(cmd, errout),
  File "/glade/u/home/samrabin/ctsm_pylib-update/cime/CIME/utils.py", line 175, in expect
    raise exc_type(msg)
CIME.utils.CIMEError: ERROR: module command /glade/u/apps/dav/opt/lmod/7.7.29/libexec/lmod python purge  failed with message:
/bin/sh: /glade/u/apps/dav/opt/lmod/7.7.29/libexec/lmod: No such file or directory

Stdout:
---- building a base case -------
---- creating a base case -------
---- base case created ------
---- base case setup ------

----------------------------------------------------------------------
Ran 20 tests in 16.412s

FAILED (errors=2)
```

**Comment by wwieder** [comment]
Is this related to the make file?

**Comment by samsrabin** [comment]
No; it happens with straight-up `./run_ctsm_py_tests --sys` too.

**Comment by wwieder** [comment]
won't fix, but have in record...
