### ISSUE TITLE
Get make all clean on the ctsm5.2 branch

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#2418]
### Brief summary of bug

``` bash
cd python
make all
```
is not clean on the ctsm5.2.mksurfdata branch. We need this working to bring to master.

### General bug information

**CTSM version you are using:** alpha-ctsm5.2.mksrf.23_ctsm5.1.dev171-5-g76217f249 (although it predates this)

**Does this bug cause significantly incorrect results in the model's science?** No
**Configurations affected:** Just python tools testing

### Details of bug

The python sys tests fail as well as the python lint checking.

### Important output or errors that show the problem
make stest fails..
``` text
...E
Stdout:
---- building a base case -------
---- creating a base case -------
---- base case created ------
---- base case setup ------
using this version: latest
---- cloning the base case in /glade/derecho/scratch/erik/tmp/tmp28jgfdnd/BART.transient

======================================================================
ERROR: test_one_site (test.test_sys_run_neon.TestSysRunNeon)
This test specifies a site to run
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/glade/work/erik/ctsm_worktrees/ctsm5.2.mksurfdata/python/ctsm/test/test_sys_run_neon.py", line 57, in test_one_site
    main("")
  File "/glade/work/erik/ctsm_worktrees/ctsm5.2.mksurfdata/python/ctsm/site_and_regional/run_neon.py", line 238, in main
    experiment,
  File "/glade/work/erik/ctsm_worktrees/ctsm5.2.mksurfdata/python/ctsm/site_and_regional/neon_site.py", line 312, in run_case
    case.create_namelists()
  File "/glade/work/erik/ctsm_worktrees/ctsm5.2.mksurfdata/cime/CIME/case/preview_namelists.py", line 97, in create_namelists
    case=self,
  File "/glade/work/erik/ctsm_worktrees/ctsm5.2.mksurfdata/cime/CIME/utils.py", line 665, in import_and_run_sub_or_cmd
    raise e1 from None
  File "/glade/work/erik/ctsm_worktrees/ctsm5.2.mksurfdata/cime/CIME/utils.py", line 662, in import_and_run_sub_or_cmd
    cmd, cmdargs, subname, subargs, logfile, case, from_dir, timeout
  File "/glade/work/erik/ctsm_worktrees/ctsm5.2.mksurfdata/cime/CIME/utils.py", line 706, in run_sub_or_cmd
    getattr(mod, subname)(*subargs)
  File "/glade/work/erik/ctsm_worktrees/ctsm5.2.mksurfdata/cime_config/buildnml", line 372, in buildnml
    expect(rc == 0, "Command %s failed rc=%d\nout=%s\nerr=%s" % (cmd, rc, out, err))
  File "/glade/work/erik/ctsm_worktrees/ctsm5.2.mksurfdata/cime/CIME/utils.py", line 175, in expect
    raise exc_type(msg)
CIME.utils.CIMEError: ERROR: Command /glade/work/erik/ctsm_worktrees/ctsm5.2.mksurfdata/bld/build-namelist failed rc=255
out=
err=ERROR : CLM build-namelist::CLMBuildNamelist::setup_logic_lnd_tuning() : lnd_tuning_mode has a value (clm6_0_GSWP3v1) that is NOT valid. Valid values are: 'clm4_5_CRUv7' 'clm4_5_GSWP3v1' 'clm4_5_cam6.0' 'clm5_0_cam6.0' 'clm5_0_CRUv7' 'clm5_0_GSWP3v1' 'clm5_1_GSWP3v1' 'clm5_1_cam6.0'

Stdout:
---- building a base case -------
---- creating a base case -------
---- base case created ------
---- base case setup ------
using this version: latest
---- cloning the base case in /glade/derecho/scratch/erik/tmp/tmp28jgfdnd/BART.transient

----------------------------------------------------------------------
Ran 33 tests in 52.550s

FAILED (errors=1)
(ctsm_pylib) ctsm
```
make lint fails...
``` text
pylint -j 4 --rcfile=ctsm/.pylintrc --fail-under=0 ctsm
************* Module ctsm.test.test_sys_gen_mksurfdata_jobscript_multi
ctsm/test/test_sys_gen_mksurfdata_jobscript_multi.py:50:4: W0102: Dangerous default value [] as argument (dangerous-default-value)
************* Module ctsm.test.test_sys_gen_mksurfdata_jobscript_single
ctsm/test/test_sys_gen_mksurfdata_jobscript_single.py:53:4: W0102: Dangerous default value [] as argument (dangerous-default-value)
************* Module ctsm.test.test_sys_mesh_modifier
ctsm/test/test_sys_mesh_modifier.py:47:8: W0612: Unused variable 'fsurdat_in' (unused-variable)
ctsm/test/test_sys_mesh_modifier.py:150:8: W0201: Attribute 'fsurdat_in' defined outside __init__ (attribute-defined-outside-init)
ctsm/test/test_sys_mesh_modifier.py:188:8: W0201: Attribute 'fsurdat_in' defined outside __init__ (attribute-defined-outside-init)
************* Module ctsm.test.test_unit_modify_fsurdat
ctsm/test/test_unit_modify_fsurdat.py:393:0: C0301: Line too long (106/100) (line-too-long)
************* Module ctsm.toolchain.gen_mksurfdata_jobscript_single
ctsm/toolchain/gen_mksurfdata_jobscript_single.py:133:0: C0301: Line too long (103/100) (line-too-long)
ctsm/toolchain/gen_mksurfdata_jobscript_single.py:96:0: R0915: Too many statements (68/50) (too-many-statements)
ctsm/toolchain/gen_mksurfdata_jobscript_single.py:7:0: W0611: Unused import sys (unused-import)
ctsm/toolchain/gen_mksurfdata_jobscript_single.py:15:0: C0411: third party import "from CIME.XML.env_mach_specific import EnvMachSpecific" should be placed before "from ctsm import add_cime_to_path" (wrong-import-order)
ctsm/toolchain/gen_mksurfdata_jobscript_single.py:16:0: C0411: third party import "from CIME.BuildTools.configure import FakeCase" should be placed before "from ctsm import add_cime_to_path" (wrong-import-order)
************* Module ctsm.toolchain.gen_mksurfdata_jobscript_multi
ctsm/toolchain/gen_mksurfdata_jobscript_multi.py:171:0: C0301: Line too long (105/100) (line-too-long)
ctsm/toolchain/gen_mksurfdata_jobscript_multi.py:249:0: C0301: Line too long (148/100) (line-too-long)
ctsm/toolchain/gen_mksurfdata_jobscript_multi.py:373:0: C0301: Line too long (127/100) (line-too-long)
ctsm/toolchain/gen_mksurfdata_jobscript_multi.py:399:0: C0301: Line too long (109/100) (line-too-long)
ctsm/toolchain/gen_mksurfdata_jobscript_multi.py:402:0: C0301: Line too long (101/100) (line-too-long)
ctsm/toolchain/gen_mksurfdata_jobscript_multi.py:405:0: C0301: Line too long (103/100) (line-too-long)
ctsm/toolchain/gen_mksurfdata_jobscript_multi.py:409:8: W0612: Unused variable 'n_p' (unused-variable)
ctsm/toolchain/gen_mksurfdata_jobscript_multi.py:140:0: R0915: Too many statements (61/50) (too-many-statements)
************* Module ctsm.toolchain.gen_mksurfdata_namelist
ctsm/toolchain/gen_mksurfdata_namelist.py:300:20: E1101: Module 'netCDF4' has no 'Dataset' member (no-member)
ctsm/toolchain/gen_mksurfdata_namelist.py:258:0: R0915: Too many statements (335/50) (too-many-statements)

------------------------------------------------------------------
Your code has been rated at 9.97/10 (previous run: 9.97/10, +0.00)
```

**Comment by ekluzek** [comment]
@samsrabin volunteered to fix this for us (the pylint issue).

**Comment by samsrabin** [comment]
The relevant branch is the one in PR #2372.

**Comment by samsrabin** [comment]
With that merge, should this now be closed?

**Comment by ekluzek** [comment]
Yep!
