### ISSUE TITLE
FATES Parameter Modification not working on izumi

### ISSUE THREAD

**Issue by adrifoster** [ESCOMP/CTSM#2454]
### Brief summary of bug

The test `ERS_D_Ld15.f45_f45_mg37.I2000Clm50FatesRs.izumi_nag.clm-FatesColdTwoStream`, which previously worked on izumi is now failing, seemingly because the conda environment is not being loaded correctly

### General bug information

**CTSM version you are using:** ctsm5.1.dev175

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** Trying to use python libraries within the izumi `run_sys_tests`

### Details of bug

```
RUN: /scratch/cluster/afoster/tests_0404-115752iz/ERS_D_Ld15.f45_f45_mg37.I2000Clm50FatesRs.izumi_nag.clm-FatesColdTwoStream.GC.0404-115752iz_nag/shell_commands
FROM: /scratch/cluster/afoster/tests_0404-115752iz/ERS_D_Ld15.f45_f45_mg37.I2000Clm50FatesRs.izumi_nag.clm-FatesColdTwoStream.GC.0404-115752iz_nag
  stat: 1

  errput: Traceback (most recent call last):
  File "/home/afoster/CTSM/src/fates/tools/modify_fates_paramfile.py", line 26, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Leaving broken case dir /scratch/cluster/afoster/tests_0404-115752iz/ERS_D_Ld15.f45_f45_mg37.I2000Clm50FatesRs.izumi_nag.clm-FatesColdTwoStream.GC.0404-115752iz_nag
ERROR: Command: '/scratch/cluster/afoster/tests_0404-115752iz/ERS_D_Ld15.f45_f45_mg37.I2000Clm50FatesRs.izumi_nag.clm-FatesColdTwoStream.GC.0404-115752iz_nag/shell_commands' failed with error 'Traceback (most recent call last):
  File "/home/afoster/CTSM/src/fates/tools/modify_fates_paramfile.py", line 26, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'' from dir '/scratch/cluster/afoster/tests_0404-115752iz/ERS_D_Ld15.f45_f45_mg37.I2000Clm50FatesRs.izumi_nag.clm-FatesColdTwoStream.GC.0404-115752iz_nag'
```

**Comment by slevis-lmwg** [comment]
This runs in ctsm5.2.008, though it still gives the #2325 expected failure.

We should remove #2454 from ExpectedTestFails.xml and close this issue.

**Comment by ekluzek** [comment]
This should be working now especially with the work I did with ctsm5.3.014. For the FATES parameter file tests you just need to make sure ctsm_pylib is activated before starting the tests now.

So we should remove from expected fails and I'll close it now.
