### ISSUE TITLE
MKSURFDATAESMF build fails in cesm2_3_alpha17d and cesm2_3_alpha17e testing

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#2519]
### Brief summary of bug

@fischer-ncar ran into this problem in both cesm2_3_alpha17d and cesm2_3_alpha17e testing. Since, this worked for us in ctsm5.2.0 it must be the difference in externals.

### General bug information

**CTSM version you are using:** ctsm5.2.0

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** just mksurfdata_emsf

### Important details of your setup / configuration so we can reproduce the bug

In both cesm2_3_beta17d and cesm2_3_beta17e

### Important output or errors that show the problem

```
PEND MKSURFDATAESMF_P128x1.f10_f10_mg37.I1850Clm50BgcCrop.derecho_intel SHAREDLIB_BUILD RERUN
 ---------------------------------------------------
2024-05-02 15:27:44: Exception during build:
Command '/glade/u/home/fischer/code/cesm2_3_alpha17e/components/clm/tools/mksurfdata_esmf/gen_mksurfdata_build --blddir /glade/derecho/scratch/fischer/t/cesm2_3_alpha17e_i/MKSURFDATAESMF_P128x1.f10_f10_mg37.I1850Clm50BgcCrop.derecho_intel.GC.c2_3_a17e_int/tool_bld' returned non-zero exit status 1. ERROR RUNNING /glade/u/home/fischer/code/cesm2_3_alpha17e/components/clm/tools/mksurfdata_esmf/gen_mksurfdata_build DETAILS IN /glade/derecho/scratch/fischer/t/cesm2_3_alpha17e_i/MKSURFDATAESMF_P128x1.f10_f10_mg37.I1850Clm50BgcCrop.derecho_intel.GC.c2_3_a17e_int/TestStatus.log

Traceback (most recent call last):
  File "/glade/u/home/fischer/code/cesm2_3_alpha17e/components/clm/cime_config/SystemTests/mksurfdataesmf.py", line 91, in build_phase
subprocess.check_call(f"{build_script_path} --blddir {self._tool_bld}", shell=True)
  File "/glade/u/apps/derecho/23.09/opt/._view/dmewvyohndr7lajyom5grftguonqfbdr/lib/python3.10/subprocess.py", line 369, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/glade/u/home/fischer/code/cesm2_3_alpha17e/components/clm/tools/mksurfdata_esmf/gen_mksurfdata_build --blddir /glade/derecho/scratch/fischer/t/cesm2_3_alpha17e_i/MKSURFDATAESMF_P128x1.f10_f10_mg37.I1850Clm50BgcCrop.derecho_intel.GC.c2_3_a17e_int/tool_bld' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/glade/u/home/fischer/code/cesm2_3_alpha17e/cime/CIME/SystemTests/system_tests_common.py", line 191, in build
self.build_phase(
  File "/glade/u/home/fischer/code/cesm2_3_alpha17e/components/clm/cime_config/SystemTests/mksurfdataesmf.py", line 94, in build_phase
sys.exit(
SystemExit: Command '/glade/u/home/fischer/code/cesm2_3_alpha17e/components/clm/tools/mksurfdata_esmf/gen_mksurfdata_build --blddir /glade/derecho/scratch/fischer/t/cesm2_3_alpha17e_i/MKSURFDATAESMF_P128x1.f10_f10_mg37.I1850Clm50BgcCrop.derecho_intel.GC.c2_3_a17e_int/tool_bld' returned non-zero exit status 1. ERROR RUNNING /glade/u/home/fischer/code/cesm2_3_alpha17e/components/clm/tools/mksurfdata_esmf/gen_mksurfdata_build DETAILS IN /glade/derecho/scratch/fischer/t/cesm2_3_alpha17e_i/MKSURFDATAESMF_P128x1.f10_f10_mg37.I1850Clm50BgcCrop.derecho_intel.GC.c2_3_a17e_int/TestStatus.log
```

**Comment by ekluzek** [comment]
Looks like the main problem is that the test assumes a CTSM checkout and needs to be updated to work in a CESM checkout.

**Comment by ekluzek** [comment]
The namelist generation also fails for similar reasons.
