### ISSUE TITLE
subset_data is broken

### ISSUE THREAD

**Issue by wwieder** [ESCOMP/CTSM#2527]
### Brief summary of bug

subset_data fails for a point when cbh and cth are not given and a dominant pft is defined.
@samsrabin suggested a python fix is pretty straight forward, but we need to also add testing around subset_data.
### General bug information

**CTSM version you are using:** [output of `git describe`]
CTSM5.2.001

**Does this bug cause significantly incorrect results in the model's science?** [Yes / No]
No

**Configurations affected:** [Fill this in if known.]
Subset data for single point cases

### Details of bug
Subset data fails if cbh and cth are not given.  This seems to have come in with the PLUMBER2 PR to b4bdev, which introduced information on canopy top and bottom heights.

### Important details of your setup / configuration so we can reproduce the bug

```
  ./subset_data point --lat 38.9592 --lon 253.0102 --create-surface --outdir /glade/derecho/scratch/wwieder/nldas/gothic/ --site Gothic_evergreen --dompft 1
Traceback (most recent call last):
  File "./subset_data", line 37, in <module>
    main()
  File "/glade/u/home/wwieder/CTSM/tools/site_and_regional/../../python/ctsm/subset_data.py", line 713, in main
    subset_point(args, file_dict)
  File "/glade/u/home/wwieder/CTSM/tools/site_and_regional/../../python/ctsm/subset_data.py", line 604, in subset_point
    specify_fsurf_out=file_dict["fsurf_out"],
  File "/glade/u/home/wwieder/CTSM/tools/site_and_regional/../../python/ctsm/site_and_regional/single_point_case.py", line 503, in create_surfdata_at_point
    f_out = self.modify_surfdata_atpoint(f_tmp)
  File "/glade/u/home/wwieder/CTSM/tools/site_and_regional/../../python/ctsm/site_and_regional/single_point_case.py", line 418, in modify_surfdata_atpoint
    zip_pfts = zip(self.dom_pft, self.pct_pft, self.cth, self.cbh)
TypeError: zip argument #3 must support iteration

```

**Comment by wwieder** [comment]
@samsrabin do you want to open a PR to fix this, or should I?  Regardless, I could use some help re. testing.

**Comment by samsrabin** [comment]
It's probably best to start a PR with just the testing (which will fail), then add the fix to make sure the test passes. So I'll add myself as assignee here.

**Comment by samsrabin** [comment]
And for my reference: The solution is to replace
```python
zip_pfts = zip(self.dom_pft, self.pct_pft, self.cth, self.cbh)
```
with
```python
cth_to_zip = self.cth
if cth_to_zip is None:
    cth_to_zip = [None for x in self.dom_pft]
zip_pfts = zip(self.dom_pft, self.pct_pft, cth_to_zip, self.cbh)
```
and do the same thing for `self.cbh`.

**Comment by samsrabin** [comment]
Revert changes in [ba0a3c](https://github.com/ESCOMP/CTSM/pull/2155/commits/ba0a3c256515b6aaa872bac84f8fdfa89fd91673) to ensure testing fails if scalar values provided.
