### ISSUE TITLE
mksurfdata_esmf FAILS in CESM checkouts; use CTSM instead

### ISSUE THREAD

**Issue by adamrher** [ESCOMP/CTSM#2658]
### Brief summary of bug

In **cesm tags**, the mksurfdata_esmf tools "gen_mksurfdata_namelist" gives an error that it can't find the correct ccs_config directory. It seems to think that ccs_config is located at cesm/components/clm/ccs_config/ when it's actually located at cesm/ccs_config/ in cesm tags.

### General bug information

cesm3_0_beta01

### Details of bug

Error message:

```
(npl) 1016 /glade/u/home/aherring> ./gen_mksurfdata_namelist --res ne0np4.ARCTIC.ne30x4 --start-year 1979 --end-year 1979 --model-mesh $work/grids/var-res/ne0np4.ARCTIC.ne30x4/grids/ne0ARCTICne30x4_esmf_c200727.nc --model-mesh-nx 117398 --model-mesh-ny 1
Traceback (most recent call last):
  File "/glade/campaign/cgd/amp/aherring/src/cesm3_0_beta01/components/clm/tools/mksurfdata_esmf/./gen_mksurfdata_namelist", line 34, in <module>
    main()
  File "/glade/campaign/cgd/amp/aherring/src/cesm3_0_beta01/components/clm/tools/mksurfdata_esmf/../../python/ctsm/toolchain/gen_mksurfdata_namelist.py", line 329, in main
    determine_output_mesh(res, force_model_mesh_file, input_path, rawdata_files)
  File "/glade/campaign/cgd/amp/aherring/src/cesm3_0_beta01/components/clm/tools/mksurfdata_esmf/../../python/ctsm/toolchain/gen_mksurfdata_namelist.py", line 760, in determine_output_mesh
    tree2 = ET.parse(xml_path)
            ^^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl/lib/python3.11/xml/etree/ElementTree.py", line 1218, in parse
    tree.parse(source, parser)
  File "/glade/u/apps/opt/conda/envs/npl/lib/python3.11/xml/etree/ElementTree.py", line 569, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/glade/campaign/cgd/amp/aherring/src/cesm3_0_beta01/components/clm/cime/../ccs_config/component_grids_nuopc.xml'
```

**Comment by wwieder** [comment]
You're right @adamrher, we can't currently run mksurfdata_esmf from CESM tags.  This is something we need to support for the CESM3 release

**Comment by lkemmons** [comment]
@wwieder is this still the case (e.g., cesm3_0_beta05)?
What is the recommended procedure?
Could the README (at https://github.com/ESCOMP/CTSM/tree/master/tools/mksurfdata_esmf) be updated?
Thanks!

**Comment by wwieder** [comment]
@slevis-lmwg can you help on this

**Comment by slevis-lmwg** [comment]
@lkemmons if I'm understanding correctly, an immediate fix that you could try involves changing the hardwired path in this line
`xml_path = os.path.join(path_to_cime(), "../ccs_config/component_grids_nuopc.xml")`
in this file
`components/clm/python/ctsm/toolchain/gen_mksurfdata_namelist.py`
according to Adam's comment posted at the top of this issue.

A sustainable solution may be to make this path modifiable by the user. Or have the code try the first path and, if it fails, try the second path. Maybe that's better.

**Comment by lkemmons** [comment]
Yes, I fixed that, but then ran into an error
with gen_mksurfdata_jobscript_single.
I just checked out ctsm5.3.069 from https://github.com/ESCOMP/CTSM
and the scripts there ran fine.

**Comment by slevis-lmwg** [comment]
#3581 seems related
#3761 may also address a similar issue (among other things)
