### ISSUE TITLE
SSP/SSPMATRIX test problems with new case github workflow

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#2913]
This is in ctsm5.3.015              

The SSPMATRIX test on Izumi is failing with this problem. I think this is a problem with the new workflow of saving the case details to a local git repository, and likely will be fixed with the next updates to cime.

```
2024-12-18 13:10:33: ERROR: Command: 'git -C /scratch/cluster/erik/tests_ctsm5315acl/SSPMATRIXCN_Ly5_Mmpi-serial.1x1_numaIA.I2000Clm50BgcCropQianRs.izumi_intel.clm-ciso_monthly.GC.ctsm5315acl_int commit -m "
ERROR: RUN FAIL: Command '  /scratch/cluster/erik/tests_ctsm5315acl/SSPMATRIXCN_Ly5_Mmpi-serial.1x1_numaIA.I2000Clm50BgcCropQianRs.izumi_intel.clm-ciso_monthly.GC.ctsm5315acl_int/bld/cesm.exe   >> cesm.log.$LID 2>&1 ' failed
See log file for details: /scratch/cluster/erik/tests_ctsm5315acl/SSPMATRIXCN_Ly5_Mmpi-serial.1x1_numaIA.I2000Clm50BgcCropQianRs.izumi_intel.clm-ciso_monthly.GC.ctsm5315acl_int.step0-AD/run/cesm.log.707138.izumi.cgd.ucar.edu.241218-131031"' failed with error 'On branch SSPMATRIXCN_Ly5_Mmpi-serial.1x1_numaIA.I2000Clm50BgcCropQianRs.izumi_intel.clm-ciso_monthly.GC.ctsm5315acl_int
nothing to commit, working tree clean' from dir '/scratch/cluster/erik/tests_ctsm5315acl/SSPMATRIXCN_Ly5_Mmpi-serial.1x1_numaIA.I2000Clm50BgcCropQianRs.izumi_intel.clm-ciso_monthly.GC.ctsm5315acl_int.step0-AD'
```

_Originally posted by @ekluzek in https://github.com/ESCOMP/CTSM/issues/2900#issuecomment-2552207685_

**Comment by ekluzek** [comment]
I'm still seeing this in ctsm5.3.016 and think it will take some more work to get working. The SSP and SSPMATRIX tests were based on older testing code and could be refactored to use system_tests_compare_two or system_tests_compare_n.py. The update would probably increase robustness and future protect these tests as well.

The PVT.py test and some others may need similar treatment.

**Comment by ekluzek** [comment]
One problem I did see is that the final test run is one of the clones made rather than the original test. I think rearranging the order so that the final test run is the original test would help this. That was something arbitrarily done when these tests were made that now with changes has caused a problem. I also realized that the ERI test still does things similar to the SSP tests and modeling what it does might help here. So it might not need a refactoring to use the system_tests_compare*.py infrastructure, and likely that might be easier.

**Comment by ekluzek** [comment]
I played around with this a bit, but didn't get it working.

I think some code similar to this needs to be added to handle the drv rpointer file.

``` python
+        drvrest = "rpointer.cpl"
+        drvrest += self._rest_time
+        self._set_drv_restart_pointer(drvrest)
```
One catch is that _rest_time doesn't work in above, without using self._set_restart_interval. So that needs to be added in.

**Comment by ekluzek** [comment]
Running ctsm_sci testlist on ctsm5.3.016 the only unexpected fail was this one:

SSP_Ld4.f09_g17.I1850Clm50BgcCrop.derecho_intel.clm-ciso_rtmColdSSP

**Comment by samsrabin** [comment]
I'm seeing this too. Some more info, from the end of `TestStatus.log`:
```
 ---------------------------------------------------
2025-01-29 14:41:59: Copying hist files to suffix 'step0-AD'
  Copying hist files for model 'clm'
    Copying '/scratch/cluster/samrabin/tests_0129-131155iz/SSPMATRIXCN_Ly5_Mmpi-serial.1x1_numaIA.I2000Clm50BgcCropQianRs.izumi_intel.clm-ciso_monthly.C.0129-131155iz.step0-AD/run/SSPMATRIXCN_Ly5_Mmpi-serial.1x1_numaIA.I2000Clm50BgcCropQianRs.izumi_intel.clm-ciso_monthly.C.0129-131155iz.step0-AD.clm2.h0.2005-01-01-00
000.nc' to '/scratch/cluster/samrabin/tests_0129-131155iz/SSPMATRIXCN_Ly5_Mmpi-serial.1x1_numaIA.I2000Clm50BgcCropQianRs.izumi_intel.clm-ciso_monthly.C.0129-131155iz.step0-AD/run/SSPMATRIXCN_Ly5_Mmpi-serial.1x1_numaIA.I2000Clm50BgcCropQianRs.izumi_intel.clm-ciso_monthly.C.0129-131155iz.step0-AD.clm2.h0.2005-01-01-000
00.nc.step0-AD'
  Copying hist files for model 'clm'
    Copying '/scratch/cluster/samrabin/tests_0129-131155iz/SSPMATRIXCN_Ly5_Mmpi-serial.1x1_numaIA.I2000Clm50BgcCropQianRs.izumi_intel.clm-ciso_monthly.C.0129-131155iz.step0-AD/run/SSPMATRIXCN_Ly5_Mmpi-serial.1x1_numaIA.I2000Clm50BgcCropQianRs.izumi_intel.clm-ciso_monthly.C.0129-131155iz.step0-AD.clm2.h1.2004-12-08-00
000.nc' to '/scratch/cluster/samrabin/tests_0129-131155iz/SSPMATRIXCN_Ly5_Mmpi-serial.1x1_numaIA.I2000Clm50BgcCropQianRs.izumi_intel.clm-ciso_monthly.C.0129-131155iz.step0-AD/run/SSPMATRIXCN_Ly5_Mmpi-serial.1x1_numaIA.I2000Clm50BgcCropQianRs.izumi_intel.clm-ciso_monthly.C.0129-131155iz.step0-AD.clm2.h1.2004-12-08-000
00.nc.step0-AD'

 ---------------------------------------------------
2025-01-29 14:42:01: Exception during run:
'/scratch/cluster/samrabin/archive/SSPMATRIXCN_Ly5_Mmpi-serial.1x1_numaIA.I2000Clm50BgcCropQianRs.izumi_intel.clm-ciso_monthly.C.0129-131155iz.step0-AD/rest/2005-01-01-00000/rpointer.cpl.2005-01-01-00000' and '/scratch/cluster/samrabin/tests_0129-131155iz/SSPMATRIXCN_Ly5_Mmpi-serial.1x1_numaIA.I2000Clm50BgcCropQianRs
.izumi_intel.clm-ciso_monthly.C.0129-131155iz.step1-SASU/run/rpointer.cpl.2005-01-01-00000' are the same file
Traceback (most recent call last):
  File "/home/samrabin/ctsm_reduce-log-noise-2736/cime/CIME/SystemTests/system_tests_common.py", line 446, in run
    self.run_phase()
  File "/home/samrabin/ctsm_reduce-log-noise-2736/cime_config/SystemTests/sspmatrixcn.py", line 251, in run_phase
    shutil.copy(item, rundir)
  File "/cluster/anaconda-23.11.0/lib/python3.11/shutil.py", line 419, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/cluster/anaconda-23.11.0/lib/python3.11/shutil.py", line 236, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: '/scratch/cluster/samrabin/archive/SSPMATRIXCN_Ly5_Mmpi-serial.1x1_numaIA.I2000Clm50BgcCropQianRs.izumi_intel.clm-ciso_monthly.C.0129-131155iz.step0-AD/rest/2005-01-01-00000/rpointer.cpl.2005-01-01-00000' and '/scratch/cluster/samrabin/tests_0129-131155iz/SSPMATRIXCN_Ly5_Mmpi-serial.1x1_numaIA.I
2000Clm50BgcCropQianRs.izumi_intel.clm-ciso_monthly.C.0129-131155iz.step1-SASU/run/rpointer.cpl.2005-01-01-00000' are the same file
```
This is in `/scratch/cluster/samrabin/tests_0129-131155iz/SSPMATRIXCN_Ly5_Mmpi-serial.1x1_numaIA.I2000Clm50BgcCropQianRs.izumi_intel.clm-ciso_monthly.C.0129-131155iz/`.

**Comment by ekluzek** [comment]
We actually have this working in an PR that I hope to bring to b4b-dev right away.

**Comment by ekluzek** [comment]
Fixed in #2921 on b4b-dev
