### ISSUE TITLE
Python 3 problem in SSP test

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#974]
### Brief summary of bug

There's a divide in the SSP ssp.py test that converts a STOP_N integer to a real.
I think this only 

### General bug information

**CTSM version you are using:** release-clm5.0.32

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** SSP tests

### Details of bug

These are the standard tests that faii:

SSP_D_Ld10.f19_g17.I1850Clm50Bgc.cheyenne_intel.clm-rtmColdSSP		
SSP_D_Ld4.f09_g17.I1850Clm50BgcCrop.cheyenne_intel.clm-ciso_rtmColdSSP		
SSP_Ld10.f19_g17.I1850Clm50Bgc.cheyenne_intel.clm-rtmColdSSP

### Important output or errors that show the problem

> Exception during run:
> ERROR: Wrong type for entry id 'STOP_N'
> Traceback (most recent call last):
>   File "/glade/work/erik/ctsm_rel2300ext/cime/scripts/Tools/../../scripts/lib/CIME/SystemTests/system_tests_common.py", line 146, in run
>     self.run_phase()
>   File "/glade/work/erik/ctsm_rel2300ext/cime_config/SystemTests/ssp.py", line 60, in run_phase
>     clone.set_value("STOP_N",stop_n1)
>   File "/glade/work/erik/ctsm_rel2300ext/cime/scripts/Tools/../../scripts/lib/CIME/case/case.py", line 379, in set_value
>     result = env_file.set_value(item, value, subgroup, ignore_type)
>   File "/glade/work/erik/ctsm_rel2300ext/cime/scripts/Tools/../../scripts/lib/CIME/XML/env_base.py", line 177, in set_value
>     val = self._set_value(node, value, vid, subgroup, ignore_type, compclass=comp)
>   File "/glade/work/erik/ctsm_rel2300ext/cime/scripts/Tools/../../scripts/lib/CIME/XML/env_base.py", line 194, in _set_value
>     val = EntryID._set_value(self, node, value, vid, subgroup, ignore_type)
>   File "/glade/work/erik/ctsm_rel2300ext/cime/scripts/Tools/../../scripts/lib/CIME/XML/entry_id.py", line 224, in _set_value
>     str_value = self.get_valid_value_string(node, value, vid, ignore_type)
>   File "/glade/work/erik/ctsm_rel2300ext/cime/scripts/Tools/../../scripts/lib/CIME/XML/entry_id.py", line 235, in get_valid_value_string
>     str_value = convert_to_string(value, type_str, vid)
>   File "/glade/work/erik/ctsm_rel2300ext/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 1163, in convert_to_string
>     expect(isinstance(value, six.integer_types), "Wrong type for entry id '{}'".format(vid))
>   File "/glade/work/erik/ctsm_rel2300ext/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 130, in expect
>     raise exc_type(msg)
> SystemExit: ERROR: Wrong type for entry id 'STOP_N'

**Comment by ekluzek** [comment]
I committed this, and tested with it, but didn't get the commit pushed to my branch. So this still needs to come to the release branch.
